spring:
  application:
    name: leo-ai-gen-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leo_ai_gen?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: clx740329
  session:
    store-type: redis
    timeout: 2592000
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.leo.leoaigenplatform.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn